package com.dbkj.account.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFavorable<M extends BaseFavorable<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setBegintime(java.util.Date begintime) {
		set("begintime", begintime);
	}

	public java.util.Date getBegintime() {
		return get("begintime");
	}

	public void setEndtime(java.util.Date endtime) {
		set("endtime", endtime);
	}

	public java.util.Date getEndtime() {
		return get("endtime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setRate(java.lang.Float rate) {
		set("rate", rate);
	}

	public java.lang.Float getRate() {
		return getFloat("rate");
	}

	public void setMincharge(java.math.BigDecimal mincharge) {
		set("mincharge", mincharge);
	}

	public java.math.BigDecimal getMincharge() {
		return get("mincharge");
	}

	public void setMaxcharge(java.math.BigDecimal maxcharge) {
		set("maxcharge", maxcharge);
	}

	public java.math.BigDecimal getMaxcharge() {
		return get("maxcharge");
	}

}
