package com.dbkj.account.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserVoiceAudit<M extends BaseUserVoiceAudit<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return getLong("userid");
	}

	public void setVId(java.lang.Long vId) {
		set("v_id", vId);
	}

	public java.lang.Long getVId() {
		return getLong("v_id");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setFilename(java.lang.String filename) {
		set("filename", filename);
	}

	public java.lang.String getFilename() {
		return getStr("filename");
	}

	public void setVoicename(java.lang.String voicename) {
		set("voicename", voicename);
	}

	public java.lang.String getVoicename() {
		return getStr("voicename");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setChecktime(java.util.Date checktime) {
		set("checktime", checktime);
	}

	public java.util.Date getChecktime() {
		return get("checktime");
	}

	public void setCheckuser(java.lang.Long checkuser) {
		set("checkuser", checkuser);
	}

	public java.lang.Long getCheckuser() {
		return getLong("checkuser");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}

	public java.lang.String getReason() {
		return getStr("reason");
	}

}
