package com.dbkj.account.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperaAction<M extends BaseOperaAction<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setOperaType(java.lang.Long operaType) {
		set("opera_type", operaType);
	}

	public java.lang.Long getOperaType() {
		return getLong("opera_type");
	}

	public void setActionId(java.lang.Long actionId) {
		set("action_id", actionId);
	}

	public java.lang.Long getActionId() {
		return getLong("action_id");
	}

}
