package com.dbkj.account.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAction<M extends BaseUserAction<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAuthId(java.lang.Long authId) {
		set("auth_id", authId);
	}

	public java.lang.Long getAuthId() {
		return getLong("auth_id");
	}

	public void setActionId(java.lang.Long actionId) {
		set("action_id", actionId);
	}

	public java.lang.Long getActionId() {
		return getLong("action_id");
	}

}
