package com.dbkj.account.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfoReset<M extends BaseUserInfoReset<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUrlstring(java.lang.String urlstring) {
		set("urlstring", urlstring);
	}

	public java.lang.String getUrlstring() {
		return getStr("urlstring");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}

	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setTrycount(java.lang.Integer trycount) {
		set("trycount", trycount);
	}

	public java.lang.Integer getTrycount() {
		return getInt("trycount");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setEmailtime(java.util.Date emailtime) {
		set("emailtime", emailtime);
	}

	public java.util.Date getEmailtime() {
		return get("emailtime");
	}

	public void setPhonetime(java.util.Date phonetime) {
		set("phonetime", phonetime);
	}

	public java.util.Date getPhonetime() {
		return get("phonetime");
	}

}
