package com.dbkj.account.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserVoice<M extends BaseUserVoice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}

	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public void setUploadtime(java.util.Date uploadtime) {
		set("uploadtime", uploadtime);
	}

	public java.util.Date getUploadtime() {
		return get("uploadtime");
	}

	public void setFilename(java.lang.String filename) {
		set("filename", filename);
	}

	public java.lang.String getFilename() {
		return getStr("filename");
	}

	public void setFilepath(java.lang.String filepath) {
		set("filepath", filepath);
	}

	public java.lang.String getFilepath() {
		return getStr("filepath");
	}

	public void setVoicename(java.lang.String voicename) {
		set("voicename", voicename);
	}

	public java.lang.String getVoicename() {
		return getStr("voicename");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setAvailable(java.lang.Boolean available) {
		set("available", available);
	}

	public java.lang.Boolean getAvailable() {
		return get("available");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
