package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Action extends BaseAction<Action> {
	public static final Action dao = new Action().dao();
}
