package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseAdminRoleAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRoleAuth extends BaseAdminRoleAuth<AdminRoleAuth> {
	public static final AdminRoleAuth dao = new AdminRoleAuth().dao();
}
