package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseAdminAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminAction extends BaseAdminAction<AdminAction> {
	public static final AdminAction dao = new AdminAction().dao();
}
