package com.dbkj.account.model;

import java.util.ArrayList;
import java.util.List;

import com.dbkj.account.config.SqlContext;
import com.dbkj.account.model.base.BaseAdminAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminAuth extends BaseAdminAuth<AdminAuth> {
	public static final AdminAuth dao = new AdminAuth().dao();
	
	public List<AdminAuth> getAuthList(String authIds){
		String sql= SqlContext.getSqlByFreeMarker(AdminAuth.class, "getAuthList");
		String[] arr=authIds.split(",");
		if(arr.length>0){
			List<Object> list=new ArrayList<Object>();
			StringBuilder where=new StringBuilder(" (");
			for(int i=0;i<arr.length;i++){
				where.append("?");
				if(i!=arr.length-1){
					where.append(",");
				}
				list.add(arr[i]);
			}
			where.append(")");
			sql=sql+where.toString();
			return find(sql,list.toArray(new Object[list.size()]));
		}
		return new ArrayList<AdminAuth>();
	}
}
