package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseAlert;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Alert extends BaseAlert<Alert> {
	public static final Alert dao = new Alert().dao();
}
