package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseFavorable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Favorable extends BaseFavorable<Favorable> {
	public static final Favorable dao = new Favorable().dao();
}
