package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseOperaAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperaAction extends BaseOperaAction<OperaAction> {
	public static final OperaAction dao = new OperaAction().dao();
}
