package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseOperaType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperaType extends BaseOperaType<OperaType> {
	public static final OperaType dao = new OperaType().dao();
	
}
