package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAction extends BaseUserAction<UserAction> {
	public static final UserAction dao = new UserAction().dao();
}
