package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAuth extends BaseUserAuth<UserAuth> {
	public static final UserAuth dao = new UserAuth().dao();
	
}
