package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserRoleAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRoleAuth extends BaseUserRoleAuth<UserRoleAuth> {
	public static final UserRoleAuth dao = new UserRoleAuth().dao();
}
