package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRecharge extends BaseUserRecharge<UserRecharge> {
	public static final UserRecharge dao = new UserRecharge().dao();
}
