package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserInfoReset;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfoReset extends BaseUserInfoReset<UserInfoReset> {
	public static final UserInfoReset dao = new UserInfoReset().dao();
}
