package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserLog201708;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLog201708 extends BaseUserLog201708<UserLog201708> {
	public static final UserLog201708 dao = new UserLog201708().dao();
}
