package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserVoiceAudit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserVoiceAudit extends BaseUserVoiceAudit<UserVoiceAudit> {
	public static final UserVoiceAudit dao = new UserVoiceAudit().dao();
}
