package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserInfoHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfoHistory extends BaseUserInfoHistory<UserInfoHistory> {
	public static final UserInfoHistory dao = new UserInfoHistory().dao();
}
