package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserMail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMail extends BaseUserMail<UserMail> {
	public static final UserMail dao = new UserMail().dao();
}
