package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserEmailReset;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserEmailReset extends BaseUserEmailReset<UserEmailReset> {
	public static final UserEmailReset dao = new UserEmailReset().dao();
}
