package com.dbkj.account.model;

import com.dbkj.account.model.base.BaseUserVoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserVoice extends BaseUserVoice<UserVoice> {
	public static final UserVoice dao = new UserVoice().dao();
	
}
